### ISSUE TITLE
Resolved 4xx Errors - Now 504 Error.

### ISSUE THREAD

**Issue by lthuynh** [OPSWAT/metadefender-teamcity-plugin#2]
Follow-up on previous Issue, Re: Receiving 4xx Errors When Submitting Files from TeamCity Builds:

In moving forward with the OPSWAT Metadefender TeamCity Plugin, we have:

1. Downloaded version 1.0.0.48
2. Updated our TeamCity Server with this new version
3. Added the suggested CSRF settings
4. Switched over to the new "v4" API URL

We are now receiving a 504 error, with **_error: Invalid use of SingleClientConnManager: connection still allocated.  Make sure to release the connection before allocating another one_**.

![Screen Shot 2021-02-08 at 3 26 49 PM](https://user-images.githubusercontent.com/5567312/107283521-1ba28480-6a22-11eb-8718-e6ec136eb539.png)

![Screen Shot 2021-02-08 at 3 28 54 PM](https://user-images.githubusercontent.com/5567312/107283718-615f4d00-6a22-11eb-801f-196040357572.png)

![Screen Shot 2021-02-08 at 3 29 42 PM](https://user-images.githubusercontent.com/5567312/107283795-7d62ee80-6a22-11eb-9a6e-a15fbb5a2574.png)

<img width="824" alt="Screen Shot 2021-02-08 at 1 45 05 PM" src="https://user-images.githubusercontent.com/5567312/107283383-f31a8a80-6a21-11eb-8532-d4ed614e7098.png">

**Comment by petya2164** [comment]
@lthuynh The 504 error looks like a gateway timeout, which might indicate a connection issue. Would it be possible to verify network connectivity in your TeamCity Agent/Server to make sure that you can connect to `api.metadefender.com`?

For example, can you run a command like this in your TeamCity build to upload a file manually?:
```
curl -X POST https://api.metadefender.com/v4/file -H 'apikey: YOUR_APIKEY' -H 'content-type: application/octet-stream' -d @/path/to/file
```

Btw, we are not able to reproduce this issue in our Linux TeamCity cluster, we are running TeamCity Professional 2020.2.2 (build 85899). Maybe this issue only affects older versions. Can you share your TeamCity version?

Could you also share the first 6 characters of your apikey (not the full string)? This will help us with finding any relevant issues in our logs.

Thanks a lot!

**Comment by lthuynh** [comment]
Hello @petya2164

The commandline curl test worked without any problems.

![Screen Shot 2021-02-09 at 11 47 27 AM](https://user-images.githubusercontent.com/5567312/107405479-fe76c000-6acc-11eb-855e-9ec22ebcb395.png)

Our current version of TeamCity Server is the same as you've noted:   2020.2.2 (build 85899)

![Screen Shot 2021-02-09 at 11 52 42 AM](https://user-images.githubusercontent.com/5567312/107405840-5a414900-6acd-11eb-8bf1-a18e7b66d696.png)

![Screen Shot 2021-02-09 at 11 52 49 AM](https://user-images.githubusercontent.com/5567312/107405846-5d3c3980-6acd-11eb-8494-67d3876e4216.png)

**Comment by petya2164** [comment]
@lthuynh Thank you for the quick confirmation!
We will change the httpclient dependencies in the plugin and create a new build for you. This should be useful to reproduce the issue.

**Comment by horvvpeter** [comment]
@lthuynh However we couldn't reproduce 504 errors we could find a bug when retrying a request after a failure. The 504 errors might have been temporary issues which could have been solved by a simple retry.

Could you please try the [latest release](https://github.com/OPSWAT/metadefender-teamcity-plugin/releases/tag/1.0.0.50) and tell us if it solves your issue? We have fixed the retry bug and also updated the httpclient dependency.

Thank you!

**Comment by lthuynh** [comment]
@horvvpeter - It appears that this latest release has resolved the issue.

An interesting thing to note...there were actually multiple submissions, and multiple failures, so it does not seem likely that it was a temporary issue.

![Screen Shot 2021-02-11 at 8 57 59 PM](https://user-images.githubusercontent.com/5567312/107726483-b1524400-6cae-11eb-8781-9147965d40e8.png)

**Comment by horvvpeter** [comment]
Hello @lthuynh !

Thank you very much for your response! I'm glad that this solved the problem.

By temporary issue I meant a temporary network issue which can happen between your TC server and MetaDefender Cloud during polling the results. We are not sure what causes them as we couldn't reproduce it and we don't see any issues on our side with your requests.

I'm closing this issue but feel free to open a new one if you experience any bugs.
